# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/victor/Desktop/Flash/DynamicMLP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/victor/Desktop/Flash/DynamicMLP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/Desktop/Flash/DynamicMLP/CMakeFiles /home/victor/Desktop/Flash/DynamicMLP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/Desktop/Flash/DynamicMLP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DynamicMLP

# Build rule for target.
DynamicMLP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DynamicMLP
.PHONY : DynamicMLP

# fast build rule for target.
DynamicMLP/fast:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/build
.PHONY : DynamicMLP/fast

# target to build an object file
IActivationFunction.o:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/IActivationFunction.o
.PHONY : IActivationFunction.o

# target to preprocess a source file
IActivationFunction.i:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/IActivationFunction.i
.PHONY : IActivationFunction.i

# target to generate assembly for a file
IActivationFunction.s:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/IActivationFunction.s
.PHONY : IActivationFunction.s

# target to build an object file
Layer.o:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Layer.o
.PHONY : Layer.o

# target to preprocess a source file
Layer.i:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Layer.i
.PHONY : Layer.i

# target to generate assembly for a file
Layer.s:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Layer.s
.PHONY : Layer.s

# target to build an object file
MultiLayerPerceptron.o:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/MultiLayerPerceptron.o
.PHONY : MultiLayerPerceptron.o

# target to preprocess a source file
MultiLayerPerceptron.i:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/MultiLayerPerceptron.i
.PHONY : MultiLayerPerceptron.i

# target to generate assembly for a file
MultiLayerPerceptron.s:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/MultiLayerPerceptron.s
.PHONY : MultiLayerPerceptron.s

# target to build an object file
Node.o:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Node.o
.PHONY : Node.o

# target to preprocess a source file
Node.i:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Node.i
.PHONY : Node.i

# target to generate assembly for a file
Node.s:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Node.s
.PHONY : Node.s

# target to build an object file
Trainer.o:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Trainer.o
.PHONY : Trainer.o

# target to preprocess a source file
Trainer.i:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Trainer.i
.PHONY : Trainer.i

# target to generate assembly for a file
Trainer.s:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/Trainer.s
.PHONY : Trainer.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/DynamicMLP.dir/build.make CMakeFiles/DynamicMLP.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DynamicMLP"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IActivationFunction.o"
	@echo "... IActivationFunction.i"
	@echo "... IActivationFunction.s"
	@echo "... Layer.o"
	@echo "... Layer.i"
	@echo "... Layer.s"
	@echo "... MultiLayerPerceptron.o"
	@echo "... MultiLayerPerceptron.i"
	@echo "... MultiLayerPerceptron.s"
	@echo "... Node.o"
	@echo "... Node.i"
	@echo "... Node.s"
	@echo "... Trainer.o"
	@echo "... Trainer.i"
	@echo "... Trainer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

